var searchData=
[
  ['makes_20lamp_20different_0',['What makes Lamp++ different?',['../index.html#autotoc_md10',1,'']]],
  ['management_20and_20copying_1',['Memory management and copying',['../using_tensor.html#autotoc_md56',1,'']]],
  ['manipulating_20gradients_2',['Checking and manipulating gradients',['../using_autograd.html#autotoc_md33',1,'']]],
  ['manipulation_3',['Shape manipulation',['../using_tensor.html#autotoc_md45',1,'']]],
  ['mathematical_20functions_4',['Mathematical functions',['../using_tensor.html#autotoc_md51',1,'']]],
  ['matrix_20operations_5',['Matrix operations',['../using_tensor.html#autotoc_md55',1,'']]],
  ['matrixmultiplication_6',['MatrixMultiplication',['../structlmp_1_1autograd_1_1ops_1_1MatrixMultiplication.html',1,'lmp::autograd::ops']]],
  ['matrixmultiplicationbackward_7',['MatrixMultiplicationBackward',['../structlmp_1_1autograd_1_1ops_1_1MatrixMultiplicationBackward.html',1,'lmp::autograd::ops']]],
  ['maxfunctor_8',['MaxFunctor',['../structlmp_1_1tensor_1_1detail_1_1cpu_1_1MaxFunctor.html',1,'lmp::tensor::detail::cpu']]],
  ['maximum_9',['Maximum',['../structlmp_1_1autograd_1_1ops_1_1Maximum.html',1,'lmp::autograd::ops']]],
  ['maximumbackward_10',['MaximumBackward',['../structlmp_1_1autograd_1_1ops_1_1MaximumBackward.html',1,'lmp::autograd::ops']]],
  ['memory_20layout_11',['Memory layout',['../using_tensor.html#autotoc_md63',1,'']]],
  ['memory_20management_20and_20copying_12',['Memory management and copying',['../using_tensor.html#autotoc_md56',1,'']]],
  ['memory_20usage_13',['Memory usage',['../using_autograd.html#autotoc_md36',1,'']]],
  ['might_20be_20perfect_20if_14',['This might be perfect if...',['../index.html#autotoc_md15',1,'']]],
  ['minfunctor_15',['MinFunctor',['../structlmp_1_1tensor_1_1detail_1_1cpu_1_1MinFunctor.html',1,'lmp::tensor::detail::cpu']]],
  ['minimum_16',['Minimum',['../structlmp_1_1autograd_1_1ops_1_1Minimum.html',1,'lmp::autograd::ops']]],
  ['minimumbackward_17',['MinimumBackward',['../structlmp_1_1autograd_1_1ops_1_1MinimumBackward.html',1,'lmp::autograd::ops']]],
  ['module_18',['Module',['../classlmp_1_1nets_1_1Module.html',1,'lmp::nets']]],
  ['moduleimpl_19',['ModuleImpl',['../classlmp_1_1nets_1_1ModuleImpl.html',1,'lmp::nets']]],
  ['mulfunctor_20',['MulFunctor',['../structlmp_1_1tensor_1_1detail_1_1cpu_1_1MulFunctor.html',1,'lmp::tensor::detail::cpu']]],
  ['multiply_21',['Multiply',['../structlmp_1_1autograd_1_1ops_1_1Multiply.html',1,'lmp::autograd::ops']]],
  ['multiplybackward_22',['MultiplyBackward',['../structlmp_1_1autograd_1_1ops_1_1MultiplyBackward.html',1,'lmp::autograd::ops']]]
];
