var searchData=
[
  ['s_20in_20the_20docs_0',['What&apos;s in the docs',['../index.html#autotoc_md13',1,'']]],
  ['sequentialimpl_1',['SequentialImpl',['../classlmp_1_1nets_1_1SequentialImpl.html',1,'lmp::nets']]],
  ['shape_20manipulation_2',['Shape manipulation',['../using_tensor.html#autotoc_md45',1,'']]],
  ['sigmoidimpl_3',['SigmoidImpl',['../classlmp_1_1nets_1_1SigmoidImpl.html',1,'lmp::nets']]],
  ['sine_4',['Sine',['../structlmp_1_1autograd_1_1ops_1_1Sine.html',1,'lmp::autograd::ops']]],
  ['sinebackward_5',['SineBackward',['../structlmp_1_1autograd_1_1ops_1_1SineBackward.html',1,'lmp::autograd::ops']]],
  ['sinfunctor_6',['SinFunctor',['../structlmp_1_1tensor_1_1detail_1_1cpu_1_1SinFunctor.html',1,'lmp::tensor::detail::cpu']]],
  ['softmaximpl_7',['SoftmaxImpl',['../classlmp_1_1nets_1_1SoftmaxImpl.html',1,'lmp::nets']]],
  ['solutions_8',['Common issues and solutions',['../getting_started.html#autotoc_md9',1,'']]],
  ['specific_20elements_9',['Working with specific elements',['../using_tensor.html#autotoc_md59',1,'']]],
  ['specific_20optimizations_10',['Device-specific optimizations',['../using_tensor.html#autotoc_md62',1,'']]],
  ['sqrtfunctor_11',['SqrtFunctor',['../structlmp_1_1tensor_1_1detail_1_1cpu_1_1SqrtFunctor.html',1,'lmp::tensor::detail::cpu']]],
  ['squareroot_12',['SquareRoot',['../structlmp_1_1autograd_1_1ops_1_1SquareRoot.html',1,'lmp::autograd::ops']]],
  ['squarerootbackward_13',['SquareRootBackward',['../structlmp_1_1autograd_1_1ops_1_1SquareRootBackward.html',1,'lmp::autograd::ops']]],
  ['squeeze_14',['Squeeze',['../structlmp_1_1autograd_1_1ops_1_1Squeeze.html',1,'lmp::autograd::ops']]],
  ['squeezebackward_15',['SqueezeBackward',['../structlmp_1_1autograd_1_1ops_1_1SqueezeBackward.html',1,'lmp::autograd::ops']]],
  ['started_16',['started',['../index.html#autotoc_md11',1,'Getting started'],['../getting_started.html',1,'Getting Started']]],
  ['steps_17',['Next steps',['../using_tensor.html#autotoc_md65',1,'']]],
  ['storage_18',['Storage',['../classlmp_1_1tensor_1_1Storage.html',1,'lmp::tensor']]],
  ['storageimpl_19',['StorageImpl',['../classlmp_1_1tensor_1_1Storage_1_1StorageImpl.html',1,'lmp::tensor::Storage']]],
  ['structure_20',['Training loop structure',['../using_autograd.html#autotoc_md30',1,'']]],
  ['subfunctor_21',['SubFunctor',['../structlmp_1_1tensor_1_1detail_1_1cpu_1_1SubFunctor.html',1,'lmp::tensor::detail::cpu']]],
  ['subtract_22',['Subtract',['../structlmp_1_1autograd_1_1ops_1_1Subtract.html',1,'lmp::autograd::ops']]],
  ['subtractbackward_23',['SubtractBackward',['../structlmp_1_1autograd_1_1ops_1_1SubtractBackward.html',1,'lmp::autograd::ops']]],
  ['sumfunctor_24',['SumFunctor',['../structlmp_1_1tensor_1_1detail_1_1cpu_1_1SumFunctor.html',1,'lmp::tensor::detail::cpu']]],
  ['summation_25',['Summation',['../structlmp_1_1autograd_1_1ops_1_1Summation.html',1,'lmp::autograd::ops']]],
  ['summationbackward_26',['SummationBackward',['../structlmp_1_1autograd_1_1ops_1_1SummationBackward.html',1,'lmp::autograd::ops']]],
  ['support_27',['With CUDA support',['../getting_started.html#autotoc_md3',1,'']]]
];
