var searchData=
[
  ['checking_20and_20manipulating_20gradients_0',['Checking and manipulating gradients',['../using_autograd.html#autotoc_md32',1,'']]],
  ['checkstream_1',['CheckStream',['../classlmp_1_1detail_1_1CheckStream.html',1,'lmp::detail']]],
  ['clamp_2',['Clamp',['../structlmp_1_1autograd_1_1ops_1_1Clamp.html',1,'lmp::autograd::ops']]],
  ['clampbackward_3',['ClampBackward',['../structlmp_1_1autograd_1_1ops_1_1ClampBackward.html',1,'lmp::autograd::ops']]],
  ['clampfunctor_4',['ClampFunctor',['../structlmp_1_1tensor_1_1detail_1_1cpu_1_1ClampFunctor.html',1,'lmp::tensor::detail::cpu']]],
  ['common_20issues_20and_20solutions_5',['Common issues and solutions',['../getting_started.html#autotoc_md9',1,'']]],
  ['comparison_20operations_6',['Comparison operations',['../using_tensor.html#autotoc_md51',1,'']]],
  ['complete_20example_7',['Complete example',['../using_autograd.html#autotoc_md37',1,'']]],
  ['computation_20graph_8',['computation graph',['../using_autograd.html#autotoc_md24',1,'Operations and the computation graph'],['../using_autograd.html#autotoc_md30',1,'Understanding the computation graph']]],
  ['considerations_9',['considerations',['../using_tensor.html#autotoc_md60',1,'Performance considerations'],['../using_autograd.html#autotoc_md34',1,'Performance considerations']]],
  ['contributing_10',['Contributing',['../index.html#autotoc_md16',1,'']]],
  ['converting_20back_20to_20vectors_11',['Converting back to vectors',['../using_tensor.html#autotoc_md43',1,'']]],
  ['copies_12',['Views vs. copies',['../using_tensor.html#autotoc_md56',1,'']]],
  ['copy_13',['copy',['../classlmp_1_1tensor_1_1Tensor.html#aca131b4b0fb7585bc9a170e9e31afe62',1,'lmp::tensor::Tensor']]],
  ['copying_14',['copying',['../using_tensor.html#autotoc_md57',1,'Explicit copying'],['../using_tensor.html#autotoc_md55',1,'Memory management and copying']]],
  ['cosfunctor_15',['CosFunctor',['../structlmp_1_1tensor_1_1detail_1_1cpu_1_1CosFunctor.html',1,'lmp::tensor::detail::cpu']]],
  ['cosine_16',['Cosine',['../structlmp_1_1autograd_1_1ops_1_1Cosine.html',1,'lmp::autograd::ops']]],
  ['cosinebackward_17',['CosineBackward',['../structlmp_1_1autograd_1_1ops_1_1CosineBackward.html',1,'lmp::autograd::ops']]],
  ['cpuoffsetutil_18',['CPUOffsetUtil',['../classlmp_1_1tensor_1_1detail_1_1cpu_1_1CPUOffsetUtil.html',1,'lmp::tensor::detail::cpu']]],
  ['creates_20gradient_20nodes_19',['What creates gradient nodes',['../using_autograd.html#autotoc_md25',1,'']]],
  ['creating_20tensors_20',['Creating tensors',['../using_tensor.html#autotoc_md38',1,'']]],
  ['creating_20variables_21',['Creating Variables',['../using_autograd.html#autotoc_md22',1,'']]],
  ['cuda_20support_22',['With CUDA support',['../getting_started.html#autotoc_md3',1,'']]],
  ['current_20todo_23',['current todo',['../md_docs_2TODOS.html#autotoc_md18',1,'']]]
];
