var searchData=
[
  ['t_20for_20you_20if_0',['This probably isn&apos;t for you if...',['../index.html#autotoc_md14',1,'']]],
  ['tanfunctor_1',['TanFunctor',['../structlmp_1_1tensor_1_1detail_1_1cpu_1_1TanFunctor.html',1,'lmp::tensor::detail::cpu']]],
  ['tangent_2',['Tangent',['../structlmp_1_1autograd_1_1ops_1_1Tangent.html',1,'lmp::autograd::ops']]],
  ['tangentbackward_3',['TangentBackward',['../structlmp_1_1autograd_1_1ops_1_1TangentBackward.html',1,'lmp::autograd::ops']]],
  ['tensor_4',['tensor',['../classlmp_1_1tensor_1_1Tensor.html',1,'lmp::tensor::Tensor'],['../classlmp_1_1tensor_1_1Tensor.html#af1ba2c1ca5c144f1a5a24a107dc26a26',1,'lmp::tensor::Tensor::Tensor()']]],
  ['tensor_20properties_5',['Tensor properties',['../using_tensor.html#autotoc_md42',1,'']]],
  ['tensorhelper_6',['TensorHelper',['../structlmp_1_1autograd_1_1TensorHelper.html',1,'lmp::autograd']]],
  ['tensorimpl_7',['tensorimpl',['../classlmp_1_1tensor_1_1TensorImpl.html',1,'lmp::tensor::TensorImpl'],['../classlmp_1_1tensor_1_1TensorImpl.html#a995bb139809ce281b69980d34b8c82d0',1,'lmp::tensor::TensorImpl::TensorImpl()']]],
  ['tensormetahandler_8',['TensorMetaHandler',['../classlmp_1_1tensor_1_1detail_1_1TensorMetaHandler.html',1,'lmp::tensor::detail']]],
  ['tensoropfact_9',['TensorOpFact',['../structlmp_1_1tensor_1_1TensorOpFact.html',1,'lmp::tensor']]],
  ['tensors_10',['tensors',['../using_tensor.html#autotoc_md38',1,'Creating tensors'],['../using_tensor.html',1,'Working with Tensors']]],
  ['tensors_20vs_20variables_11',['When to use tensors vs. variables',['../using_autograd.html#autotoc_md36',1,'']]],
  ['tensors_20with_20gradient_20tracking_12',['Variables: Tensors with gradient tracking',['../using_autograd.html#autotoc_md21',1,'']]],
  ['tests_13',['Running tests',['../getting_started.html#autotoc_md7',1,'']]],
  ['the_20backward_20pass_14',['The backward pass',['../using_autograd.html#autotoc_md26',1,'']]],
  ['the_20basic_20build_15',['The basic build',['../getting_started.html#autotoc_md2',1,'']]],
  ['the_20big_20picture_16',['The big picture',['../using_autograd.html#autotoc_md20',1,'']]],
  ['the_20computation_20graph_17',['the computation graph',['../using_autograd.html#autotoc_md24',1,'Operations and the computation graph'],['../using_autograd.html#autotoc_md30',1,'Understanding the computation graph']]],
  ['the_20docs_18',['What&apos;s in the docs',['../index.html#autotoc_md13',1,'']]],
  ['the_20examples_19',['Running the examples',['../getting_started.html#autotoc_md6',1,'']]],
  ['this_20might_20be_20perfect_20if_20',['This might be perfect if...',['../index.html#autotoc_md15',1,'']]],
  ['this_20probably_20isn_20t_20for_20you_20if_21',['This probably isn&apos;t for you if...',['../index.html#autotoc_md14',1,'']]],
  ['to_22',['to',['../classlmp_1_1tensor_1_1Tensor.html#aa7d6b7a69b19532e7e33720b1008c73f',1,'lmp::tensor::Tensor::to()'],['../structlmp_1_1autograd_1_1ops_1_1To.html',1,'lmp::autograd::ops::To']]],
  ['to_20use_20tensors_20vs_20variables_23',['When to use tensors vs. variables',['../using_autograd.html#autotoc_md36',1,'']]],
  ['to_20vectors_24',['Converting back to vectors',['../using_tensor.html#autotoc_md43',1,'']]],
  ['to_5fvector_25',['to_vector',['../classlmp_1_1tensor_1_1Tensor.html#ad1757577dbdd9503fa2cfbb1532cf187',1,'lmp::tensor::Tensor']]],
  ['tobackward_26',['ToBackward',['../structlmp_1_1autograd_1_1ops_1_1ToBackward.html',1,'lmp::autograd::ops']]],
  ['todo_27',['current todo',['../md_docs_2TODOS.html#autotoc_md18',1,'']]],
  ['todos_28',['TODOS',['../md_docs_2TODOS.html',1,'']]],
  ['tracking_29',['Variables: Tensors with gradient tracking',['../using_autograd.html#autotoc_md21',1,'']]],
  ['training_20loop_20structure_30',['Training loop structure',['../using_autograd.html#autotoc_md29',1,'']]],
  ['transformfunctor_31',['TransformFunctor',['../structlmp_1_1tensor_1_1detail_1_1cpu_1_1internal_1_1TransformFunctor.html',1,'lmp::tensor::detail::cpu::internal']]],
  ['transpose_32',['Transpose',['../structlmp_1_1autograd_1_1ops_1_1Transpose.html',1,'lmp::autograd::ops']]],
  ['transposebackward_33',['TransposeBackward',['../structlmp_1_1autograd_1_1ops_1_1TransposeBackward.html',1,'lmp::autograd::ops']]],
  ['transposition_34',['Transposition',['../using_tensor.html#autotoc_md47',1,'']]],
  ['type_20promotion_35',['Type promotion',['../using_tensor.html#autotoc_md63',1,'']]],
  ['typemeta_36',['TypeMeta',['../structlmp_1_1tensor_1_1TypeMeta.html',1,'lmp::tensor']]],
  ['typemeta_3c_20bool_20_3e_37',['TypeMeta&lt; bool &gt;',['../structlmp_1_1tensor_1_1TypeMeta_3_01bool_01_4.html',1,'lmp::tensor']]],
  ['typemeta_3c_20double_20_3e_38',['TypeMeta&lt; double &gt;',['../structlmp_1_1tensor_1_1TypeMeta_3_01double_01_4.html',1,'lmp::tensor']]],
  ['typemeta_3c_20float_20_3e_39',['TypeMeta&lt; float &gt;',['../structlmp_1_1tensor_1_1TypeMeta_3_01float_01_4.html',1,'lmp::tensor']]],
  ['typemeta_3c_20int_20_3e_40',['TypeMeta&lt; int &gt;',['../structlmp_1_1tensor_1_1TypeMeta_3_01int_01_4.html',1,'lmp::tensor']]],
  ['typemeta_3c_20int16_5ft_20_3e_41',['TypeMeta&lt; int16_t &gt;',['../structlmp_1_1tensor_1_1TypeMeta_3_01int16__t_01_4.html',1,'lmp::tensor']]],
  ['typemeta_3c_20int64_5ft_20_3e_42',['TypeMeta&lt; int64_t &gt;',['../structlmp_1_1tensor_1_1TypeMeta_3_01int64__t_01_4.html',1,'lmp::tensor']]],
  ['types_43',['Data types',['../using_tensor.html#autotoc_md40',1,'']]],
  ['types_20and_20options_44',['Build types and options',['../getting_started.html#autotoc_md4',1,'']]]
];
