name: Doxygen Documentation Deployment
on:
  push:
    branches: [ main ] 
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write 
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Install Doxygen
        run: sudo apt-get update && sudo apt-get install build-essential doxygen cmake -y
        
      - name: Generate Doxygen Documentation
        run: |
             cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug -DENABLE_CUDA=off
             cmake --build build --target docs
        
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4.2.0
        with:
          target_branch: gh-pages
          build_dir: docs/html
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
